### ISSUE TITLE
Question: Will this repository be participating in the hacktoberfest?

### ISSUE THREAD

**Issue by harsh18262** [pacstall/pacstall-programs#345]
Hi,
Will this repository or the project be available for the hacktoberfest event?

**Comment by Henryws** [comment]
Could you explain more of what hacktoberfest is?

**Comment by RDKRACZ** [comment]
https://twitter.com/hacktoberfest
https://hacktoberfest.digitalocean.com/
https://www.digitalocean.com/blog/hacktoberfest-is-back-2021/
https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/

**Comment by Henryws** [comment]
I'm going to call in the big brains on this one

@wizard-28

**Comment by wizard-28** [comment]
Looks good to me.

@Henryws a tl;dr regarding Hacktoberfest for you:
1. We as maintainers participate in this fest by registering, then marking this repo with the topic "hacktoberfest"
2. People ( other participants ) then can contribute to this repository by making pull requests. When they get merged the participant ( contributor ) gets points.
3. All pull requests from October 1 - 31 count in this fest. The maintainers themselves can participate and contribute to their own repository.
4. At the end the participants can win prizes, T-shirts etc.

A lot of *potential* spam PRs can come due to participation in this fest, marking those PRs as "invalid" or "spam", will prevent those from being counted.

We could register even on the last day. The system will automatically count the PRs for the full month of October regardless.

Here's a FAQ: https://hacktoberfest.digitalocean.com/faq

**Comment by wizard-28** [comment]
@Henryws @wizard-28 @NarutoXY @D-Brox 

React with 👍🏼 signifying an **agreement** on participation in the Hacktoberfest this year.
React with 👎🏼 signifying a **disagreement** on participation in the Hacktoberfest this year.

*This poll is only for owners. Other contributors can react to this [issue's first message](https://github.com/pacstall/pacstall-programs/issues/345#issue-1012487593) directly.*

**Comment by NarutoXY** [comment]
Yay Let's do this. Other fellow users can react to this comment to show their reaction towards this decision

**Comment by wizard-28** [comment]
Both repos are now participating. Closing this issue.
