### ISSUE TITLE
PacReq: `doas-git`

### ISSUE THREAD

**Issue by marzeq** [pacstall/pacstall-programs#591]
doas is an alternative to sudo, that aims to provide 95% of sudo's functionality while having a substantially smaller codebase. It was originally created for the OpenBSD project, but has been ported to Linux.

URL: https://github.com/slicer69/doas
Building Guide: https://github.com/slicer69/doas#installing-build-tools

**Comment by wizard-28** [comment]
As a side note, while I make this script we already have [`opendoas-git`](https://github.com/pacstall/pacstall-programs/blob/master/packages/opendoas-git/opendoas-git.pacscript) in our repository, so you can check that out.

**Comment by wizard-28** [comment]
Also, since you are new to this repository I gotta clarify that you don't need to make a `PacReq` every time you want something added to this repository. If you are able to you could *directly* make a PR and we'll merge that.

`PacReq`s (*Pac*kage *Req*uests) are for packages that you request *others* to make. If you are unable to make them yourself.
