### ISSUE TITLE
PacReq: Vesktop

### ISSUE THREAD

**Issue by flysqu** [pacstall/pacstall-programs#6204]
### Types

-git (Compiled off of the latest commit of the package), -deb (Debian achieve release of the package)

### URL

https://github.com/Vencord/Vesktop

### Building guide

https://github.com/Vencord/Vesktop?tab=readme-ov-file#building-from-source
https://github.com/Vencord/Vesktop/releases

### Additional context

discord's offical app has in my experience pretty jank support for linux most of all screensharing which vesktop does a lot better :3
(first link for build guide, second for deb's)

**Comment by vbrabandt2005** [comment]
Weirdly enough, I wrote the pacscript before reading your package request, but was hesitant to submit it because although I'm currently daily-driving it, I'm not sure if I will use it forever, but yeah I have summited PR #6207, so if everything goes fine, it should be available in the pacstall repo soon.

**Comment by flysqu** [comment]
yay thats sick! will close :3
